### ISSUE TITLE
Define minimum required version of Mojolicious

### ISSUE THREAD

**Issue by reneeb** [yowcow/p5-MojoX-Session-Simple#3]
You are using the methods secrets in your testfiles. That method was added in Mojolicious 4.63

**Comment by yowcow** [comment]
Thanks for pointing that out!

**Comment by reneeb** [comment]
As a side note: In the Changes file you can still find the name MojoX-Session-Adapter-PSGI

**Comment by yowcow** [comment]
Thanks again for the report.  I've updated and released version 0.04. :bow:
